import shutil
import tagpy
import tagpy.id3v1
import pathlib

from tempfile import TemporaryDirectory


def test_can_tag():
    with TemporaryDirectory() as tempdir:
        tempfile = pathlib.Path(tempdir).joinpath("la.mp3")
        shutil.copy(pathlib.Path(__file__).parent.joinpath("la.mp3"), tempfile)
        fileref = tagpy.FileRef(tempfile.as_posix())
        file = fileref.file()
        tag = file.ID3v1Tag(True)
        tag.genre = tagpy.id3v1.Genre(tagpy.id3v1.genreMap()["Disco"])
        file.save()


def test_has_genres():
    # There's a core set, and then there's the ones that some platforms have and others don't
    # See also https://en.wikipedia.org/wiki/List_of_ID3v1_genres
    listedGenres = set(tagpy.id3v1.genreList())
    minimumGenres = {
        "A Cappella",
        "Acid",
        "Acid Jazz",
        "Acid Punk",
        "Acoustic",
        "Alternative",
        "Alternative Rock",
        "Ambient",
        "Anime",
        "Ballad",
        "Bass",
        "Beat",
        "Big Band",
        "Black Metal",
        "Bluegrass",
        "Blues",
        "Booty Bass",
        "Cabaret",
        "Celtic",
        "Chamber Music",
        "Chanson",
        "Chorus",
        "Christian Gangsta Rap",
        "Christian Rap",
        "Christian Rock",
        "Classic Rock",
        "Classical",
        "Club",
        "Club-House",
        "Comedy",
        "Contemporary Christian",
        "Country",
        "Crossover",
        "Cult",
        "Dance",
        "Darkwave",
        "Death Metal",
        "Disco",
        "Dream",
        "Drum & Bass",
        "Drum Solo",
        "Duet",
        "Easy Listening",
        "Electronic",
        "Ethnic",
        "Euro-House",
        "Euro-Techno",
        "Eurodance",
        "Folk",
        "Folklore",
        "Freestyle",
        "Funk",
        "Game",
        "Gangsta",
        "Goa",
        "Gospel",
        "Gothic",
        "Gothic Rock",
        "Grunge",
        "Hard Rock",
        "Heavy Metal",
        "Hip-Hop",
        "House",
        "Humour",
        "Indie",
        "Industrial",
        "Instrumental",
        "Instrumental Pop",
        "Instrumental Rock",
        "Jazz",
        "Jpop",
        "Jungle",
        "Latin",
        "Lo-Fi",
        "Meditative",
        "Merengue",
        "Metal",
        "Musical",
        "National Folk",
        "Native American",
        "New Age",
        "New Wave",
        "Noise",
        "Oldies",
        "Opera",
        "Other",
        "Polka",
        "Polsk Punk",
        "Pop",
        "Pop-Folk",
        "Pop/Funk",
        "Porn Groove",
        "Power Ballad",
        "Pranks",
        "Primus",
        "Progressive Rock",
        "Psychedelic",
        "Psychedelic Rock",
        "Punk",
        "Punk Rock",
        "R&B",
        "Rap",
        "Rave",
        "Reggae",
        "Retro",
        "Revival",
        "Rhythmic Soul",
        "Rock",
        "Rock & Roll",
        "Salsa",
        "Samba",
        "Satire",
        "Showtunes",
        "Ska",
        "Slow Jam",
        "Slow Rock",
        "Sonata",
        "Soul",
        "Sound Clip",
        "Soundtrack",
        "Southern Rock",
        "Space",
        "Speech",
        "Swing",
        "Symphonic Rock",
        "Symphony",
        "Synthpop",
        "Tango",
        "Techno",
        "Techno-Industrial",
        "Terror",
        "Thrash Metal",
        "Top 40",
        "Trailer",
        "Trance",
        "Tribal",
        "Trip-Hop",
        "Vocal",
    }
    assert listedGenres.issuperset(minimumGenres), sorted(
        minimumGenres.difference(listedGenres)
    )


def test_genre_index():
    assert tagpy.id3v1.genreIndex("Disco") == 4
