FROM ubuntu:20.04
WORKDIR /work
RUN apt-get update
RUN apt-get install -y --no-install-recommends libtag1-dev libboost-python-dev python3-pip python-is-python3
RUN pip install wheel pytest
COPY . /work
RUN python setup.py bdist_wheel
RUN pip install dist/*
RUN pytest -vvv -s
