FROM alpine:3.17.0
WORKDIR /work
RUN apk add --no-cache taglib-dev python3-dev py3-pip boost1.80-python3 boost1.80-dev build-base
RUN pip install wheel pytest
COPY . /work
RUN python3 setup.py bdist_wheel
RUN pip install dist/*
RUN pytest -vvv -s
