FROM ubuntu:18.04
WORKDIR /work
RUN apt-get update
RUN apt-get install -y --no-install-recommends libtag1-dev libboost-python-dev
RUN apt-get install -y python3-pip
RUN pip3 install wheel pytest
COPY . /work
RUN python3 setup.py bdist_wheel
RUN pip3 install dist/*
RUN pytest -vvv -s
