FROM fedora:42
WORKDIR /work
RUN dnf install -y python3-pip gcc gcc-c++ taglib-devel boost-python3-devel python3-devel
RUN pip install wheel pytest setuptools==75.7.0
COPY . /work
RUN python3 setup.py bdist_wheel
RUN pip install dist/*
RUN pytest -vvv -s
