FROM ubuntu:24.04
WORKDIR /work
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y --no-install-recommends libtag1-dev libboost-python-dev python3-pip python-is-python3 build-essential
RUN pip install --break-system-packages pytest==8.4.2
COPY . /work
RUN python setup.py bdist_wheel
RUN pip install --break-system-packages dist/*
RUN pytest -vvv -s
