FROM alpine:3.21.0
WORKDIR /work
RUN apk add --no-cache taglib-dev python3-dev py3-pip boost1.84-python3 boost1.84-dev build-base
RUN pip install --break-system-packages wheel==0.45.1 pytest==8.4.2
COPY . /work
RUN python3 setup.py bdist_wheel
RUN pip install --break-system-packages dist/*
RUN pytest -vvv -s
