FROM ubuntu:18.04
WORKDIR /work
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y --no-install-recommends libtag1-dev libboost-python-dev python3-pip build-essential
RUN pip3 install wheel pytest setuptools
COPY . /work
RUN python3 setup.py bdist_wheel
RUN pip3 install dist/*
RUN pytest -vvv -s
